# Generated by Django 5.1.4 on 2024-12-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arxiv_id', models.CharField(max_length=50, unique=True, verbose_name='arXiv ID')),
                ('title_en', models.CharField(max_length=500, verbose_name='English Title')),
                ('title_cn', models.CharField(max_length=500, verbose_name='Chinese Title')),
                ('abstract_en', models.TextField(verbose_name='English Abstract')),
                ('abstract_cn', models.TextField(verbose_name='Chinese Abstract')),
                ('authors', models.TextField(verbose_name='Authors')),
                ('published_date', models.DateTimeField(verbose_name='Published Date')),
                ('updated_date', models.DateTimeField(verbose_name='Updated Date')),
                ('pdf_url', models.URLField(verbose_name='PDF URL')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_date'],
            },
        ),
    ]
