# Generated by Django 5.1.4 on 2025-02-14 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_archive', models.CharField(default='arxiv', max_length=50, verbose_name='Source Archive')),
                ('entry_id', models.CharField(max_length=50, verbose_name='Entry ID')),
                ('entry_version', models.PositiveIntegerField(default=1, verbose_name='Entry Version')),
                ('title_en', models.CharField(max_length=500, verbose_name='English Title')),
                ('title_cn', models.CharField(max_length=500, verbose_name='Chinese Title')),
                ('abstract_en', models.TextField(verbose_name='English Abstract')),
                ('abstract_cn', models.TextField(verbose_name='Chinese Abstract')),
                ('published_date', models.DateTimeField(verbose_name='Article Published Date')),
                ('updated_date', models.DateTimeField(verbose_name='Article Updated Date')),
                ('comment_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='English Comment')),
                ('comment_cn', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chiness Comment')),
                ('journal_ref_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='English Journal Ref')),
                ('journal_ref_cn', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chinses Journal Ref')),
                ('doi', models.CharField(blank=True, max_length=50, null=True, verbose_name='DOI')),
                ('primary_category', models.CharField(max_length=50, verbose_name='Primary Category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('translation_validated', models.BooleanField(default=False, verbose_name='Translation Validated')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-updated_date'],
                'indexes': [models.Index(fields=['-updated_date'], name='articles_ar_updated_64c5b3_idx'), models.Index(fields=['source_archive', 'entry_id', 'entry_version'], name='articles_ar_source__547fa4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='articles.article')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='articles.article')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='articles.article')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
