# Generated by Django 5.1.4 on 2025-04-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('source_archive', 'entry_id', 'entry_version'), name='unique_article_version'),
        ),
    ]
