from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'articles'

urlpatterns = [
    path('', cache_page(60 * 5)(views.home), name='home'),
    path('index', cache_page(60 * 5)(views.home), name='index'),
    path('search', views.search, name='search_box'),
    path('search/advanced', views.search_advanced, name='search_advanced'),
    path('search/<str:archive_id>', views.search_archive, name='search_archive'),
    path('archive/', cache_page(60 * 5)(views.archive), name='archive_index'),
    path('archive/<str:archive_id>', cache_page(60 * 5)(views.archive), name='archive'),
    path('help', views.help, name='help'),
    path('help/archive/<str:archive_id>', views.help_archive_description, name='help_archive_description'),
    path('year/<str:archive>/', cache_page(60 * 5)(views.year_default), name='year_default'),
    path('year/<str:archive>/<int:year>/', cache_page(60 * 5)(views.year_view), name='year'),
    path('list/', cache_page(60 * 5)(views.list_articles), {'context': '', 'subcontext': ''}, name='list_default'),
    path('list/all', cache_page(60 * 5)(views.list_articles), {'context': 'math', 'subcontext': 'all'}, name='list_all'),
    path('list/<str:context>/<str:subcontext>', cache_page(60 * 5)(views.list_articles), name='list_articles'),
    path('catchup/', views.catchup_form, name='catchup_form'),
    path('catchup/<str:subject>/<str:date>', cache_page(60 * 5)(views.catchup), name='catchup'),
    path('author/<str:article_id>/<str:author_id>', views.author_search, name='author_search'),
    path('pdf/<str:archive>/<str:arxiv_id>.pdf', views.redirect_pdf, name='redirect_pdf_with_archive'),
    path('pdf/<str:arxiv_id>.pdf', views.redirect_pdf, name='redirect_pdf'),
    path('pdf/<str:archive>/<str:arxiv_id>', cache_page(60 * 5)(views.pdf), name='pdf_with_archive'),
    path('pdf/<str:arxiv_id>', cache_page(60 * 5)(views.pdf), name='pdf'),
    path('cn-pdf/<str:archive>/<str:arxiv_id>', views.cn_pdf, name='cn_pdf_with_archive'),
    path('cn-pdf/<str:arxiv_id>', views.cn_pdf, name='cn_pdf'),
    path('html/<str:arxiv_id>/', views.html, name='html'),
    path('html/<str:arxiv_id>', views.html, name='html_no_slash'),
    path('html/<str:archive>/<path:arxiv_id>', views.html_with_archive, name='html_with_archive'),
    path('abs', views.bare_abs, name='bare_abs'),
    path('abs/', views.abstract, {'arxiv_id': ''}, name='abstract_empty'),
    path('abs/<path:arxiv_id>', cache_page(60 * 5)(views.abstract), name='abstract'),
    path('auth/show-endorsers/<path:arxiv_id>', views.show_endorsers, name='show_endorsers'),
    path('help/mathjax', views.help_mathjax, name='help_mathjax'),
    path('dvi/<str:archive>/<str:arxiv_id>', views.dvi, name='dvi_with_archive'),
    path('dvi/<str:arxiv_id>', views.dvi, name='dvi'),
    path('ps/<str:arxiv_id>', views.ps, name='ps'),
    path('show-email/<path:show_email_hash>/<path:arxiv_id>', views.show_email, name='show_email'),
    path('format/<str:archive>/<str:arxiv_id>', cache_page(60 * 5)(views.format_view), name='format_with_archive'),
    path('format/<str:arxiv_id>', cache_page(60 * 5)(views.format_view), name='format'),
    path('src/<path:arxiv_id>/anc', views.anc_listing, name='anc_listing'),
    path('src/<path:arxiv_id>/anc/<path:file_path>', views.anc, name='anc'),
    path('e-print/<str:arxiv_id_str>', views.src, name='e_print'),
    path('e-print/<str:archive>/<str:arxiv_id_str>', views.src, name='e_print_with_archive'),
    path('src/<str:arxiv_id_str>', views.src, name='src'),
    path('src/<str:archive>/<str:arxiv_id_str>', views.src, name='src_with_archive'),
    path('prevnext', views.previous_next, name='previous_next'),
    path('bibtex/<path:arxiv_id>', views.bibtex, name='bibtex'),
    path('multi/', views.multi, name='multi'),
    path('multi/<path:path>', views.multi, name='multi_with_path'),
    path('donate', views.donate, name='donate'),
]